config/routes.rb
Rails.application.routes.draw do
  resources :sessions

  resources :gossips do 
    get 'gossips/:gossip_id', to: 'gossips#show'
    resources :comments do
    end
    resources :likes
  end
  resources :users do 
    get 'users/:user_id', to: 'users#show'
  end
  root to: 'homepage#show'
  get 'welcome/:user_entry', to: 'welcome#show'
  get 'team/show'
  get 'contact/show'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gossip
  belongs_to :user
  belongs_to :like
  has_many :poly_comments, as: :commentable 
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  belongs_to :like, optional: true
  has_many :gossip_tags
  has_many :tags, through: :gossip_tags
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :title, presence: true, length: { in: 3..14 }

  validates :content, presence: true
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip, optional: true
  has_many :comments, dependent: :destroy
end

app/models/poly_comment.rb
class PolyComment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossip_tags
  has_many :gossips, through: :gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :password, presence: true
  belongs_to :city
  has_many :gossips, dependent: :destroy
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :current_gossip, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user, only: [:create]
  before_action :is_creator, only: [:edit, :update, :destroy]

  def show
    @tags = []
    GossipTag.all.map do |el_gt|
      if current_gossip.id == el_gt.gossip_id
        Tag.all.map do |el_tag|
          if el_gt.tag_id == el_tag.id
            @tags << el_tag.title
          end
        end
      end
    end

    @count = 0
    @comments = []
    Comment.all.map do |el|
      if el.gossip_id == current_gossip.id
      @comments << el
      @count += 1
      end
    end
    @id = params[:id]
  end

  def new
  end

  def create
    g = Gossip.new(
      title: params[:gossip][:title],
      content: params[:gossip][:content],
      user: current_user
    )

    match = ''
    Tag.all.map do |el|
      if el.title == params[:gossip][:tag]
        match = el.id
      end
    end

    gt = GossipTag.new(
      gossip_id: Gossip.last.id + 1,
      tag_id: match
    )
    if g.save && gt.save
    redirect_to root_path, success: "Gossip created Successfully!"

    else 
      redirect_to new_gossip_path, danger: g.errors.full_messages && gt.errors.full_messages
    end
  end

  def edit
  end

  def update
    if @gossip.update(gossip_params)
      redirect_to root_path, success: "Gossip successfully edited !"
    else
      redirect_to edit_gossip_path(@gossip.id), danger: @gossip.errors.full_messages
    end
  end

  def destroy
    @gossip.destroy

    redirect_to root_path
  end

  private

  def gossip_params
    params.require(:gossip).permit(:title, :content)
  end

  def current_gossip
    @gossip = Gossip.find(params[:id])
  end

  def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end

  def is_creator
    unless current_user.id == @gossip.user.id 
      flash[:danger] = "What are you trying to do ? .."
      redirect_to root_path
    end
  end

end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def show
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @user = User.find(params[:user_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/likes_helper.rb
module LikesHelper

  def find_likes(thing)
    result = 0
    find_user_id = ''
    find_gossip_id = ''

    Like.all.map do |el|
      if find_user_id != el.user_id || find_gossip_id != el.gossip_id
        if el.gossip_id == thing.id  
          result += 1
          find_user_id = el.user_id
          find_gossip_id = el.gossip_id
        end
      end
    end
    return result
  end

  def is_liked?(thing)
    Like.all.map do |el|
      if el.gossip_id == thing.id
        if el.user_id == current_user.id
        return 2
        end
      end
    end
  end

  def find_like_id(thing)
    Like.all.map do |el|
      if el.gossip_id == thing.id
        if el.user_id == current_user.id
        return el.id
        end
      end
    end
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    if current_user.nil?
      return true
    else
      return false
    end
  end

end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gossips/edit.html.erb
<div class="container-welcome">
<h1>EDIT GOSSIP</h1>
</div>

<center>
<%= form_for :gossip, url: gossip_path, :method => :PUT do |form| %>

  <label for="title">Gossip title</label>
  <%= form.text_field :title %>
  <br />

  <label for="content">Gossip content</label>
  <%= form.text_area :content, size: "60x10" %>
  <br />

  <%= form.submit %>
<% end %>
</center>

app/views/gossips/new.html.erb
<div class="welcome-container">
<h1>NEW GOSSIP</h1>
</div>

<center>
<%= form_for :gossip, url: gossips_path do |form| %>
  <label for="title">Gossip title</label>
  <%= form.text_field :title %>
  <br />
  <label for="content">Gossip content</label>
  <%= form.text_area :content, size: "60x10" %>
  <br />
  <label for="content">Select a tag</label>
  <%= form.select(:tag, Tag.all.map {|el|[el.title, el.title]}) %>
  <br />
  <%= form.submit %>
<% end %>
</center>

app/views/gossips/show.html.erb
<div class="container-welcome">
<h1>Gossip</h1>
</div>

<div class="container-gossip">
<div class="gossip-infos">
<h2><%= @gossip.title %></h2>
<h6>"<%=@gossip.content%>"</h6>
<p> by : 
  <%= link_to @gossip.user.first_name, user_path(@gossip.user.id) %>
</p>
<p>created : <%= @gossip.created_at %></p>

<p> Tags : </p>
<% @tags.each do |el|%>
  <li>
  <%= el %>
  </li>
  <% end %>
</div>


<div class="gossip-comments">
<p> Il y a <%= @count %> commentaires, sur ce gossip</p>

<% if !logged_in? %>
<%= form_tag(gossip_comments_path(@id), method: 'post') do %>
  <%= text_area_tag(:content) %>
  
  <%= submit_tag("Submit") %>
<% end %>
<% end %>


<% @comments.each do |el| %>

  <li>
  <%= el.content %>
  (<%= el.user.first_name %>)
  <% if !logged_in? %>
  <% if current_user.id == el.user.id %>
  <%= link_to "edit", edit_gossip_comment_path(@gossip.id,el.id),  class: "btn btn-sm btn-warning" %>
  <%= link_to "destroy", gossip_comment_path(@gossip.id,el.id), method: "delete", data: { confirm: 'Are you sure?'},  class: "btn btn-sm btn-danger" %>
  <% end %>
  <% end %>
  </li>
 
<% end %>



</div>
</div>