config/routes.rb
Rails.application.routes.draw do
  resources :sessions

  resources :gossips do 
    get 'gossips/:gossip_id', to: 'gossips#show'
    resources :comments do
    end
    resources :likes
  end
  resources :users do 
    get 'users/:user_id', to: 'users#show'
  end
  root to: 'homepage#show'
  get 'welcome/:user_entry', to: 'welcome#show'
  get 'team/show'
  get 'contact/show'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gossip
  belongs_to :user
  belongs_to :like
  has_many :poly_comments, as: :commentable 
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  belongs_to :like, optional: true
  has_many :gossip_tags
  has_many :tags, through: :gossip_tags
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :title, presence: true, length: { in: 3..14 }

  validates :content, presence: true
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip, optional: true
  has_many :comments, dependent: :destroy
end

app/models/poly_comment.rb
class PolyComment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossip_tags
  has_many :gossips, through: :gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :password, presence: true
  belongs_to :city
  has_many :gossips, dependent: :destroy
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/likes_helper.rb
module LikesHelper

  def find_likes(thing)
    result = 0
    find_user_id = ''
    find_gossip_id = ''

    Like.all.map do |el|
      if find_user_id != el.user_id || find_gossip_id != el.gossip_id
        if el.gossip_id == thing.id  
          result += 1
          find_user_id = el.user_id
          find_gossip_id = el.gossip_id
        end
      end
    end
    return result
  end

  def is_liked?(thing)
    Like.all.map do |el|
      if el.gossip_id == thing.id
        if el.user_id == current_user.id
        return 2
        end
      end
    end
  end

  def find_like_id(thing)
    Like.all.map do |el|
      if el.gossip_id == thing.id
        if el.user_id == current_user.id
        return el.id
        end
      end
    end
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    if current_user.nil?
      return true
    else
      return false
    end
  end

end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsIntermediateThegossipproject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-dark">
      <%= link_to "Homepage", root_path, class: 'navbar_link' %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "team", team_show_path, class: 'navbar_link' %>
          </li>
          <li class="nav-item">
            <%= link_to "contact", contact_show_path, class: 'navbar_link' %>
          </li>
          <% if logged_in? %>
          <li class="nav-item">
            <%= link_to "signup", new_user_path, class: 'navbar_link' %>
          </li>
          <li class="nav-item">
            <%= link_to "login", new_session_path, class: 'navbar_link' %>
          </li>
          <% else %>
          <li class="nav-item">
            <%= link_to "logout", session_path(session.id), method: :delete, class: 'navbar_link' %>
          </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <div class="main-container">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%= name %>'>
        <center>
        <%= msg %>
        </center>
      </div>
    <% end %>
 
    <%= yield %>
    </div>
  </body>
</html>